import { useCurrentAccount, useSignAndExecuteTransaction } from "@mysten/dapp-kit";
import { Transaction } from "@mysten/sui/transactions";
import { useNetworkVariable } from "../networkConfig";
import { useState, useEffect } from "react";

// --- THEME CONSTANTS ---
const THEME = {
  bg: "#0B0F1A",        // Midnight Ink
  cardBg: "#14161F",    // Charcoal Void
  accent: "#7CFF00",    // Radioactive Green
  highlight: "#FF2F92", // Toxic Pink
  secondary: "#00E5FF", // Glitch Cyan
  border: "#2A2A35",
  inputBg: "#0f111a",
  muted: "#5c5c6b"
};

export function Mint({ onSuccess }: { onSuccess: () => void }) {
  const account = useCurrentAccount();
  
  // Form State
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [imageUrl, setImageUrl] = useState("");
  
  // --- NEW DNA STATE ---
  const [hexCode, setHexCode] = useState("0x_00_00_INIT");
  const [isMutating, setIsMutating] = useState(false);

  // We keep the attributes state so the Modal and Smart Contract still work,
  // but now it is AUTO-GENERATED by the Hex Code logic.
  const [attributes, setAttributes] = useState<{ key: string; value: string }[]>([]);

  // Initialize a random mutation on load
  useEffect(() => {
    handleMutation();
  }, []);

  // --- NEW MUTATION LOGIC ---
  const handleMutation = () => {
    setIsMutating(true);
    
    // Simulate a "hacking" decoding effect delay
    setTimeout(() => {
        // 1. Generate Random Hex Segments
        const seg1 = Math.floor(Math.random() * 255).toString(16).toUpperCase().padStart(2, '0');
        const seg2 = Math.floor(Math.random() * 255).toString(16).toUpperCase().padStart(2, '0');
        const seg3 = Math.floor(Math.random() * 999).toString().padStart(3, '0');
        
        // 2. Determine "Rarity" based on random segments (Just for flavor)
        const rarityVal = parseInt(seg1, 16);
        let mutationClass = "STANDARD";
        if (rarityVal > 200) mutationClass = "ALPHA_VARIANT";
        else if (rarityVal > 100) mutationClass = "BETA_HYBRID";
        else mutationClass = "GAMMA_DRONE";

        // 3. Construct the Visual String
        const newHex = `0x_${seg1}_${seg2}_FREQ-${seg3}`;
        setHexCode(newHex);

        // 4. Update the actual data passed to the contract
        setAttributes([
            { key: "DNA_SEQUENCE", value: newHex },
            { key: "MUTATION_CLASS", value: mutationClass },
            { key: "VOLATILITY_INDEX", value: `${seg3}%` }
        ]);

        setIsMutating(false);
    }, 400); // Short delay for effect
  };

  // Modal State
  const [showPreview, setShowPreview] = useState(false);

  // 1. VALIDATE AND OPEN MODAL
  const handleInitiate = () => {
    if (!account) return alert("⚠️ Please connect your wallet first");
    if (!name || !imageUrl) return alert("⚠️ Name and Image URL are required!");
    
    // If valid, open the preview
    setShowPreview(true);
  };

  // 2. RESET FORM AFTER SUCCESS
  const handleSuccess = () => {
    setName(""); setDescription(""); setImageUrl("");
    handleMutation(); // Reset DNA to a new random strain
    setShowPreview(false);
    onSuccess();
  };

  if (!account) return <div style={{ padding: "40px", color: THEME.secondary, fontFamily: "monospace", textAlign:"center" }}>/// CONNECTION_REQUIRED</div>;

  return (
    <div style={{ 
        padding: "40px 20px", 
        background: THEME.bg, 
        minHeight: "100vh", 
        fontFamily: "'Courier New', Courier, monospace",
        color: "white"
    }}>
      <div style={{ maxWidth: "600px", margin: "0 auto" }}>
        
        {/* HEADER */}
        <div style={{ borderBottom: `2px solid ${THEME.secondary}`, paddingBottom: "20px", marginBottom: "30px" }}>
            <h2 style={{ 
                fontSize: "36px", margin: 0, textTransform: "uppercase", 
                textShadow: `3px 3px 0px ${THEME.highlight}` 
            }}>
                🧪 Mutation <span style={{ color: THEME.secondary }}>Lab</span>
            </h2>
            <p style={{ color: THEME.accent, margin: "5px 0 0 0", fontSize: "12px", letterSpacing: "1px" }}>
                /// MINTING_PROTOCOL_V1 // CREATE_NEW_LIFEFORM
            </p>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: "20px" }}>
            
            {/* Name */}
            <div>
                <label style={{ display: "block", color: THEME.secondary, fontSize: "12px", marginBottom: "5px", textTransform: "uppercase" }}>Subject Name *</label>
                <input
                    type="text"
                    placeholder="e.g. FREAK-001"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    style={inputStyle}
                />
            </div>

            {/* Description */}
            <div>
                <label style={{ display: "block", color: THEME.secondary, fontSize: "12px", marginBottom: "5px", textTransform: "uppercase" }}>Bio / Data</label>
                <textarea
                    placeholder="Enter specimen description..."
                    value={description}
                    onChange={(e) => setDescription(e.target.value)}
                    rows={3}
                    style={inputStyle}
                />
            </div>

            {/* Image URL */}
            <div>
                <label style={{ display: "block", color: THEME.secondary, fontSize: "12px", marginBottom: "5px", textTransform: "uppercase" }}>Image Source (URL) *</label>
                <input
                    type="text"
                    placeholder="ipfs://... or https://..."
                    value={imageUrl}
                    onChange={(e) => setImageUrl(e.target.value)}
                    style={inputStyle}
                />
            </div>

            {/* --- NEW "HEX CODE HACKER" PANEL (Option 3) --- */}
            <div style={{ background: THEME.cardBg, padding: "2px", border: `1px solid ${THEME.border}`, marginTop: "10px" }}>
                {/* Panel Container */}
                <div style={{ background: "black", padding: "20px", border: `1px solid ${THEME.secondary}40`}}>
                    
                    {/* Header */}
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" }}>
                        <label style={{ color: THEME.secondary, fontWeight: "bold", textTransform: "uppercase", letterSpacing: "2px", display:"flex", alignItems:"center", gap: "8px" }}>
                            <span style={{ display:"inline-block", width:"8px", height:"8px", background:THEME.secondary, boxShadow:`0 0 5px ${THEME.secondary}`}}></span>
                            GENETIC SEQUENCE
                        </label>
                        <span style={{ fontSize: "10px", color: THEME.muted }}>AUTO_GENERATED</span>
                    </div>
                    
                    {/* The "Screen" Display */}
                    <div style={{ 
                        background: "#080a10", 
                        border: `1px solid ${THEME.border}`, 
                        padding: "20px", 
                        marginBottom: "20px",
                        position: "relative",
                        overflow: "hidden"
                    }}>
                        {/* Scanline Effect Overlay */}
                        <div style={{
                            position: "absolute", top:0, left:0, right:0, bottom:0,
                            background: "linear-gradient(rgba(18, 16, 16, 0) 50%, rgba(0, 0, 0, 0.25) 50%), linear-gradient(90deg, rgba(255, 0, 0, 0.06), rgba(0, 255, 0, 0.02), rgba(0, 0, 255, 0.06))",
                            backgroundSize: "100% 2px, 3px 100%",
                            pointerEvents: "none"
                        }}></div>

                        {/* The HEX String */}
                        <div style={{ 
                            textAlign: "center", 
                            fontSize: "24px", 
                            fontFamily: "'Courier New', monospace", 
                            fontWeight: "bold",
                            color: isMutating ? THEME.muted : THEME.accent,
                            textShadow: isMutating ? "none" : `0 0 10px ${THEME.accent}`,
                            letterSpacing: "3px",
                            transition: "all 0.2s"
                        }}>
                           {isMutating ? "/// DECODING ///" : hexCode}
                        </div>
                        
                        {/* Sub-data display */}
                        {!isMutating && (
                            <div style={{ display: "flex", justifyContent: "center", gap: "20px", marginTop: "15px", fontSize: "10px", color: "#555" }}>
                                <span>CLASS: <span style={{color: "white"}}>{attributes.find(a => a.key === "MUTATION_CLASS")?.value}</span></span>
                                <span>VOL: <span style={{color: "white"}}>{attributes.find(a => a.key === "VOLATILITY_INDEX")?.value}</span></span>
                            </div>
                        )}
                    </div>

                    {/* The Mutate Button */}
                    <button 
                        onClick={handleMutation}
                        disabled={isMutating}
                        style={{ 
                            width: "100%", 
                            padding: "12px", 
                            background: "transparent", 
                            border: `1px dashed ${THEME.secondary}`, 
                            color: THEME.secondary, 
                            cursor: "pointer", 
                            fontWeight: "bold", 
                            textTransform: "uppercase",
                            letterSpacing: "2px",
                            fontSize: "12px",
                            transition: "all 0.2s"
                        }}
                        onMouseOver={(e) => { e.currentTarget.style.background = `${THEME.secondary}20`; }}
                        onMouseOut={(e) => { e.currentTarget.style.background = "transparent"; }}
                    >
                        {isMutating ? "CALCULATING..." : "⚡ INJECT MUTAGEN (RE-ROLL)"}
                    </button>
                </div>
            </div>

            {/* Initiate Button */}
            <button
                onClick={handleInitiate}
                style={{ 
                    marginTop: "20px", 
                    width: "100%", 
                    padding: "18px", 
                    background: THEME.highlight, 
                    color: "white", 
                    border: "none", 
                    cursor: "pointer",
                    fontWeight: "900",
                    fontSize: "18px",
                    textTransform: "uppercase",
                    letterSpacing: "2px",
                    boxShadow: `5px 5px 0px ${THEME.secondary}`,
                    transition: "transform 0.1s"
                }}
            >
                ⚡ REVIEW & MINT
            </button>
        </div>
      </div>

      {/* --- PREVIEW MODAL (UNCHANGED LOGIC) --- */}
      {showPreview && (
        <MintModal 
            data={{ name, description, imageUrl, attributes }}
            onClose={() => setShowPreview(false)}
            onSuccess={handleSuccess}
        />
      )}
    </div>
  );
}

// --- SUB-COMPONENT: MINT CONFIRMATION MODAL (UNCHANGED) ---
function MintModal({ data, onClose, onSuccess }: { data: any, onClose: () => void, onSuccess: () => void }) {
    const { mutate: signAndExecute } = useSignAndExecuteTransaction();
    const packageId = useNetworkVariable("packageId");
    const [isMinting, setIsMinting] = useState(false);

    const handleConfirmMint = () => {
        setIsMinting(true);
        try {
            const tx = new Transaction();
            const attrKeys = data.attributes.map((a: any) => a.key);
            const attrValues = data.attributes.map((a: any) => a.value);

            tx.moveCall({
                target: `${packageId}::freak_marketplace::mint`, 
                arguments: [
                    tx.pure.string(data.name),
                    tx.pure.string(data.description),
                    tx.pure.string(data.imageUrl),
                    tx.pure.vector("string", attrKeys), 
                    tx.pure.vector("string", attrValues),
                ],
            });

            signAndExecute({ transaction: tx }, {
                onSuccess: () => {
                    alert("✅ SUBJECT CREATED SUCCESSFULLY!");
                    setIsMinting(false);
                    onSuccess();
                },
                onError: (err) => {
                    console.error("Mint Error:", err);
                    alert(`❌ MINT FAILED: ${err.message}`);
                    setIsMinting(false);
                },
            });
        } catch (error: any) {
            alert(`❌ ERROR: ${error.message}`);
            setIsMinting(false);
        }
    };

    return (
        <div style={{ 
            position: "fixed", top: 0, left: 0, width: "100%", height: "100%", 
            background: "rgba(0,0,0,0.85)", backdropFilter: "blur(5px)",
            display: "flex", justifyContent: "center", alignItems: "center", zIndex: 1000 
        }}>
            <div style={{ 
                width: "600px", maxWidth: "95%", background: "black", 
                border: `2px solid ${THEME.highlight}`, 
                boxShadow: `0 0 50px ${THEME.highlight}40`,
                display: "flex", flexDirection: "column"
            }}>
                 {/* HEADER */}
                <div style={{ padding: "15px 20px", borderBottom: "1px solid #333", display: "flex", justifyContent: "space-between", alignItems: "center", background: "#111" }}>
                    <h3 style={{ margin: 0, color: "white", textTransform: "uppercase", letterSpacing: "1px" }}>CONFIRM MUTATION</h3>
                    <button onClick={onClose} style={{ background: "transparent", border: "none", color: "#666", fontSize: "24px", cursor: "pointer" }}>&times;</button>
                </div>

                {/* BODY (Split View) */}
                <div style={{ padding: "20px", display: "flex", gap: "20px", flexDirection: "row" }}>
                    
                    {/* LEFT: IMAGE PREVIEW */}
                    <div style={{ flex: "1", minWidth: "200px" }}>
                        <div style={{ width: "100%", height: "250px", background: "#111", border: `1px solid ${THEME.border}`, display:"flex", alignItems:"center", justifyContent:"center", overflow: "hidden" }}>
                             {data.imageUrl ? <img src={data.imageUrl} style={{ width: "100%", height: "100%", objectFit: "cover" }} onError={(e) => (e.currentTarget.style.display = "none")} /> : "NO VISUAL"}
                        </div>
                    </div>

                    {/* RIGHT: DETAILS */}
                    <div style={{ flex: "1.2", display: "flex", flexDirection: "column", gap: "10px" }}>
                        <div>
                            <label style={{ fontSize: "10px", color: THEME.muted, textTransform: "uppercase" }}>SUBJECT NAME</label>
                            <div style={{ fontFamily: "monospace", color: THEME.secondary, fontSize: "18px", fontWeight: "bold" }}>{data.name}</div>
                        </div>

                        <div>
                            <label style={{ fontSize: "10px", color: THEME.muted, textTransform: "uppercase" }}>BIO_DATA</label>
                            <div style={{ fontFamily: "monospace", color: "#ccc", fontSize: "12px", background: "#1a1a1a", padding: "8px", borderRadius: "4px", maxHeight: "60px", overflowY: "auto" }}>
                                {data.description || "No data provided."}
                            </div>
                        </div>

                        {/* DNA PREVIEW */}
                        <div>
                            <label style={{ fontSize: "10px", color: THEME.muted, textTransform: "uppercase" }}>DNA SEQUENCE (ATTRIBUTES)</label>
                            <div style={{ display: "grid", gridTemplateColumns: "1fr", gap: "5px", marginTop: "5px" }}>
                                {data.attributes.map((attr: any, i: number) => (
                                    <div key={i} style={{ background: "#111", padding: "4px 8px", fontSize: "10px", border: "1px solid #333", color: "#aaa", display: "flex", justifyContent: "space-between" }}>
                                        <span style={{color: THEME.accent}}>{attr.key}</span> 
                                        <span>{attr.value}</span>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>

                {/* FOOTER */}
                <div style={{ padding: "20px", borderTop: "1px solid #333", display: "flex", gap: "10px" }}>
                    <button onClick={onClose} style={{ flex: 1, padding: "15px", background: "transparent", border: "1px solid #444", color: "#888", cursor: "pointer", fontWeight: "bold" }}>
                        ABORT
                    </button>
                    
                    {/* CONFIRM BUTTON */}
                    <button onClick={handleConfirmMint} disabled={isMinting} style={{ 
                        flex: 2, padding: "15px", 
                        background: THEME.highlight, 
                        border: "none", 
                        color: "white", 
                        fontWeight: "900", fontSize: "16px", letterSpacing: "2px", textTransform: "uppercase",
                        boxShadow: `4px 4px 0px ${THEME.secondary}`,
                        cursor: isMinting ? "wait" : "pointer", 
                        opacity: isMinting ? 0.7 : 1,
                        transition: "transform 0.1s"
                    }}
                    onMouseDown={(e) => e.currentTarget.style.transform = "translate(2px, 2px)"}
                    onMouseUp={(e) => e.currentTarget.style.transform = "none"}
                    >
                        {isMinting ? "MINTING..." : "CONFIRM MINT"}
                    </button>
                </div>
            </div>
        </div>
    );
}

// Shared Input Style
const inputStyle = {
    width: "100%", 
    padding: "12px", 
    background: "#0f111a", 
    border: "1px solid #333", 
    color: "white", 
    fontFamily: "monospace",
    fontSize: "14px",
    outline: "none"
};